<?php

namespace Demo\PlatformBundle\Repository;

// A decommenter si bug
// use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    // Ici, nous sommes dans le Repository de l'entité, pas besoin de faire getDoctrine()->getManager()->getRepository('.........:Advert')
    
    public function myFindAll(){
        // Methode 1 : Via l'Entity Manager
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a') // All 
            ->from($this->_entityName, 'a'); // Entity
        // Dans un repository, $this->_entityName est le namespace de l'entité gérée
        // Ici, il vaut donc Demo\PlatformBundle\Entity\Advert
        
        // Methode 2 : Raccourci
        // $this->createQueryBuilder remplis deja le SELECT et FROM
        $queryBuilder = $this->createQueryBuilder('a');
        // On n'ajoute pas de critère ou tri particulier, la construction de notre requête est finie
        
        // On récupère la Query
        $query = $queryBuilder->getQuery();
        
        // Récuperation des resultats
        $results = $query->getResult();
        
        // Retourne les resulatts
        // return $results;
        
        // Methode 3 : Raccourci de raccourci
        return $this->createQueryBuilder('a')->getQuery()->getResult();
    }
    
    public function myFindOne($id){
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.id = :id')
        ->setParameter('id', $id);
        
        return $qb->getQuery()->getResult();
    }
    
    public function findByAuthorAndDate($author, $year){
      $qb = $this->createQueryBuilder('a');
    
      $qb->where('a.author = :author')
          ->setParameter('author', $author)
         ->andWhere('a.date < :year')
          ->setParameter('year', $year)
         ->orderBy('a.date', 'DESC')
      ;
    
      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
    
    public function myFind(){
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.author = :author')
        ->setParameter('author', 'Marine');
        
        // Application de la condition sur l'annee
        $this->whereCurrentYear($qb);
        
        $qb->orderBy('a.date', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    public function myFindDQL($id){
        $query = $this->_em->createQuery('SELECT a FROM DemoPlatformBundle:Advert a WHERE a.id = :id');
        $query->setParameter('id', $id);
        
        // getSingleResult car la requete ne doit retourner qu'un résultat
        return $query->getSingleResult();
    }
    
    public function whereCurrentYear(QueryBuilder $qb){
        $qb->andWhere('a.date BETWEEN :start AND :end')
        // start : 1er janvier
        ->setParameter('start', new \DateTime(date('Y').'-01-01'))
        // end : 31 decembre
        ->setParameter('end', new \DateTime(date('Y').'-12-31'));
        // Possible de passer un array au set parameter : array('start' => date, 'end' => date)
    }
    
    public function getAdvertWithApplications(){
        $qb = $this->createQueryBuilder('a')
        ->leftJoin('a.applications', 'app', 'WITH', 'YEAR(app.date) > 2013')
        ->addSelect('app');
        
        return $qb->getQuery()->getResult();
    }
    
    public function getAdvertWithCategories(array $categoryNames){
        //SQL : Select * From advert, category, advertCategory Where category.name IN (&categoryNames)
        
        $qb -> $this->createQueryBuilder('a')
        // On fait une jointure avec l'entité Category avec pour alias « c »
        ->innerJoin('a.categories','c')
        ->addSelect('c');
        // Puis on filtre sur le nom des catégories à l'aide d'un IN
        $qb->where($qb->expr()->in('c.name', $categoryNames));
        
        // Return un tableau d'advert
        return $qb->getQuery()->getResult();
    }
    
    public function getLastAdvertsWithLimit($limit){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.id', 'DESC')
        ->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }
    
    /*
    * Recuperation de toutes les Adverts avec les images et les catégories en 1 requete
    */
    public function getAdverts($page, $nbPerPage){
        $query = $this->createQueryBuilder('a')
        ->leftJoin('a.image', 'i')
        ->addSelect('i')
        ->leftJoin('a.categories', 'c')
        ->addSelect('c')
        ->leftJoin('a.skills', 's')
        ->addSelect('s')
        ->leftJoin('s.skill', 'k')
        ->addSelect('k')
        ->orderBy('a.date', 'DESC')
        ->getQuery();
        
        $query
          // On définit l'annonce à partir de laquelle commencer la liste
         ->setFirstResult(($page-1) * $nbPerPage)
          // Ainsi que le nombre d'annonce à afficher sur une page
         ->setMaxResults($nbPerPage)
        ;
        return new Paginator($query, true);
        // return $query->getResult();
    }
    
    /*
    * Add a Where clause to the QueryBuilder to get Adverts with creation / modif date lower than param
    * @param : QueryBuilder $qb, Datetime $date
    */
    public function whereDateIsLowerParam(QueryBuilder $qb, \DateTime $date){
        $qb->AndWhere('a.updatedAt <= :date')                      // Date de modification antérieure à :date
        ->orWhere('a.updatedAt IS NULL AND a.date <= :date') // Si la date de modification est vide, on vérifie la date de création
        
        ->setParameter('date', $date);
    }
    
    /*
    * Where No Applications
    * @param : QueryBuilder $qb
    */
    public function whereNoApplications(QueryBuilder $qb){
        $qb->andWhere('a.applications IS EMPTY');
    }
    
    /*
    * Get the Adverts 
    */
    public function getAllAdverts(){
        $qb = $this->createQueryBuilder('a');
        return $qb;
    }
    
    /*
    * Recuperation de toutes les Adverts sans candidatures
    * Avec une date de creation / modification inf. a la date passee en param
    * @param : Datetime $date
    */    
    public function getAdvertsWithNoApplicationsAndDateLowerThanParam(\DateTime $date){
        $qb = $this->getAllAdverts();
        $this->whereDateIsLowerParam($qb, $date);
        $this->whereNoApplications($qb);
        return $qb->getQuery()->getResult();
        
        // $qb=$this->createQueryBuilder('a')
        // ->where('a.updatedAt <= :date')                      // Date de modification antérieure à :date
        // ->orWhere('a.updatedAt IS NULL AND a.date <= :date') // Si la date de modification est vide, on vérifie la date de création
        // ->andWhere('a.applications IS EMPTY')                // On vérifie que l'annonce ne contient aucune candidature
        // ->setParameter('date', $date);
        // return $qb->getQuery()->getResult();
    }
}
