<?php

namespace Demo\PlatformBundle\Repository;
// A decommenter si bug
// use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getApplicationsWithAdvert($limit){
        $qb->$this->createQueryBuilder('a');
        $qb->innerJoin('a.advert', 'adv')
        ->addSelect('adv');
        $qb->setMaxResults($lmit);
        
        // Return un tableau de candidatures
        return $qb->getQuery()->getResult();
    }
}
