demo_forum:
    resource: "@DemoForumBundle/Resources/config/routing.yml"
    prefix:   /forum

demo_core:
    resource: "@DemoCoreBundle/Resources/config/routing.yml"
    prefix:   /

demo_platform:
    resource: "@DemoPlatformBundle/Resources/config/routing.yml"
    prefix:    /platform