services:
#    demo_platform.example:
#        class: Demo\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    demo_platform.antispam:
        class: Demo\PlatformBundle\Antispam\DemoAntispam
        arguments: ["@mailer", %locale%, 50] # Tableau d'arguments
            # - "@mailer"
            # - %locale%
            # - 50
            # Mettre les arguments dans le tableau, les mettre hors tableau avec des tirets ne fonctionne pas
            
    demo_platform.email.application_mailer:
        class: Demo\PlatformBundle\Email\ApplicationMailer
        arguments: ["@mailer"]
        
    demo_platform.doctrine_listener.application_creation:
        class: Demo\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments: ["@demo_platform.email.application_mailer"]
        tags:
          - { name: doctrine.event_listener, event: postPersist }
          
    demo_platform.advertPurger:
        class: Demo\PlatformBundle\AdvertPurger\DemoAdvertPurger
        arguments: ["@doctrine.orm.entity_manager"]
        
    # demo_platform.AdvertForm:
    #     class: Demo\PlatformBundle\Form\AdvertType
    #     tags:
    #         - { name: form.type}