services:
#    demo_core.example:
#        class: Demo\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    demo_core.platform:
        class: Demo\PlatformBundle\Controller\AdvertController